/**
 * Return middleware satisfying:
 * post: res.locals.gameNameSessionKey is populated with the first String from
 * randomStringGenerator's output function
 * @return {Function} Express middleware that populates
 * res.locals.gameNameSessionKey with a string generated by
 * randomStringGenerator, sends 500 on error
 * @param {Function*} randomStringGenerator A generator matching the interface
 * of ../randomCapGenerator that produces a function that yields at least one
 * random string
 * @param {Function} configs An object with a cookieValueLength function that
 * returns a Number
 */
function computeGameNameSessionKey(randomStringGenerator, configs) {
  const middleware = (req, res, next) => {
    const responses = require('../../responses');
    const gen = randomStringGenerator({letters: configs.cookieValueLength()});
    res.locals.gameNameSessionKey = gen.next().value;
    if(!res.locals.gameNameSessionKey) {
      return res.status(500).send(responses.SERVER_ERROR);
    }
    return next();
  };
  return middleware;
}

module.exports = computeGameNameSessionKey;